### ISSUE TITLE
Doesn't work when minified

### ISSUE THREAD

**Issue by rxaviers** [kborchers/react-globalize#10]
React Globalize classes are generated dynamically by parsing Globalize functions argument names. This approach works well for regular non-minified files. But, when files are minified (e.g., by using uglifyjs), it breaks the correspondence between the argument names used in the markup vs. what's found in the function arguments (e.g., `a` instead of `options`).

**Comment by kborchers** [comment]
Hmm, it's a good point but I'm trying to think of any case where someone is using React without a build step in which case they should just be pulling unminified Globalize into their build and everything is fine. Not sure how big of an issue this is but will keep it open to not forget about it and allow further conversation.

**Comment by rxaviers** [comment]
It's not about using React without a build step. It's indeed about a build step. After you build it, you'll probably minify before serving on production. That's where it will break. Anyway, there's a simple solution for that, e.g., https://github.com/rxaviers/react-globalize/commit/66b8c4284d41c2349a0198a3124459f9ba5aabde

**Comment by kborchers** [comment]
You are correct. The funny part is your solution is basically what I had before reworking it to infer the API from Globalize 2084ebf29d744949efd384e38fd7066e6263f638. That's what I get for trying to be clever. How do you want to proceed? You want to send a PR to make that change or should I try to revert that commit? I think reverting could be difficult with all of the changes that have been made on top so maybe easier to just reimplement it.

**Comment by rxaviers** [comment]
> The funny part is your solution is basically what I had before reworking it to infer the API from Globalize 2084ebf. That's what I get for trying to be clever

:see_no_evil: :laughing: It's worth trying different solutions.

> How do you want to proceed?

Sure, I can submit a PR with that code. Will do it soon.
