### ISSUE TITLE
Explicitly allow globalize pre 1.1.0 releases as peer dependency

### ISSUE THREAD

**Issue by rxaviers** [kborchers/react-globalize#22]
@alunny ran into an issue installing react-globalize using globalize 1.1.0-rc.2, particularly the following error:

    npm ERR! peerinvalid Peer react-globalize@0.3.0 wants globalize@>= 1.0.0

Consider updating package.json to allow pre 1.1.0 releases.

**Comment by alunny** [comment]
Thanks!

**Comment by rxaviers** [comment]
Ywc, just let us know on any problems.
